package base

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

func BaseTestsInit() <-chan interface{} {
	ch := make(chan interface{})
	go func() interface{} {
		defer close(ch)
		defer ReturnPanicError(ch)

		retRes534 := (<-TestLanguageSpecific())
		PanicOnError(retRes534)
		TestConstants()
		TestAfterConstructor()
		TestExtend()
		TestDeepExtend()
		TestCryptography()
		TestBinaryToBase64()
		TestDatetime()
		TestDecimalToPrecision()
		TestCapitalize()
		TestNumberToString()
		TestPrecise()
		TestSafeMethods()
		TestSafeTicker()
		TestToArray()
		TestJson()
		TestSortBy()
		TestSum()
		TestUrlencodeBase64()
		TestUrlencode()
		TestOmit()
		TestGroupBy()
		TestIndexBy()
		TestInArray()
		TestFilterBy()
		TestHandleMethods()
		TestRemoveRepeatedElementsFromArray()
		TestIsEmpty()
		TestUrlencodeWithArrayRepeat()
		TestParsePrecision()
		TestPrecisionFromString()
		TestTimeframes()
		TestStrip()
		TestRawencode()
		TestStringToBase16()
		TestExtractParams()
		TestArrayConcat()
		TestArraysConcat()
		TestUuid()

		retRes924 := (<-TestSetMarketsFromExchange())
		PanicOnError(retRes924)
		TestEthMethods()
		TestKeysort()
		TestImplodeParams()
		TestUnique()
		TestUrlencodeNested()

		retRes984 := (<-TestSleep())
		PanicOnError(retRes984)
		TestIo()
		TestIsJsonEncodedObject()
		return nil
	}()
	return ch
}
