// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

import { implicitReturnType } from '../base/types.js';
import { Exchange as _Exchange } from '../base/Exchange.js';

interface Exchange {
    publicGetV1Time (params?: {}): Promise<implicitReturnType>;
    publicGetV1Symbols (params?: {}): Promise<implicitReturnType>;
    publicGetV1SymbolsSymbol (params?: {}): Promise<implicitReturnType>;
    publicGetV1SymbolsSummary (params?: {}): Promise<implicitReturnType>;
    publicGetV1SymbolsSymbolSummary (params?: {}): Promise<implicitReturnType>;
    publicGetV1SymbolsSymbolBook (params?: {}): Promise<implicitReturnType>;
    publicGetV1SymbolsSymbolCandles (params?: {}): Promise<implicitReturnType>;
}
abstract class Exchange extends _Exchange {}

export default Exchange
